const app_version = "1.0.15";

const savedVersion = localStorage.getItem("appversion");
if (savedVersion !== app_version) {
  localStorage.clear();
  localStorage.setItem("appversion", app_version);
  console.log("Data updated to version", app_version);
}

// =========== admin =====================
if (!localStorage.getItem("admin")) {
  const admin = { username: "admin", password: "admin" };
  localStorage.setItem("admin", JSON.stringify(admin));
}

// ================= USERS =================
if (!localStorage.getItem("users")) {
  const users = [
    {
      username: "user1",
      password: "123",
      locked: false,
      name: "Luan Vo",
      email: "luanvo@gmail.com",
      phoneNumber: "099912322",
      gender: "male",
      date: "2006-03-19",
      address: "Saigon University, District 5",
    },
    {
      username: "user2",
      password: "123",
      locked: true,
      name: "Vo Luan",
      email: "user2@gmail.com",
      phoneNumber: "0987654321",
      gender: "male",
      date: "2006-04-16",
      address: "Saigon University, Campus 2",
    },
  ];
  localStorage.setItem("users", JSON.stringify(users));
  console.log("User data created");
}

// ================= PRODUCT TYPES =================
if (!localStorage.getItem("productTypes")) {
  const productTypes = [
    { code: "T001", name: "Women", desc: "Casual and sport cotton shirts" },
    { code: "T002", name: "Men", desc: "Denim pants for men and women" },
    { code: "T003", name: "Accessories", desc: "Caps, belts, socks, bags..." },
    { code: "T004", name: "collection", desc: "New fashion collection" },
  ];
  localStorage.setItem("productTypes", JSON.stringify(productTypes));
}

if (!localStorage.getItem("category")) {
  const category = [
    { type: "Women", cate: "Dresses" },
    { type: "Women", cate: "Tops-Blouses" },
    { type: "Women", cate: "Bottoms" },
    { type: "Women", cate: "Outerwear" },
    { type: "Men", cate: "T-shirts-polos" },
    { type: "Men", cate: "Shirts" },
    { type: "Men", cate: "Pants-Trousers" },
    { type: "Men", cate: "Shorts" },
    { type: "Men", cate: "Outerwear" },
    { type: "Accessories", cate: "Sunglasses " },
    { type: "Accessories", cate: "Bags-Purses" },
    { type: "Accessories", cate: "Jewelry " },
    { type: "Accessories", cate: "Hats-Caps  " },
    { type: "Collection", cate: "Summer-Autumn" },
    { type: "Collection", cate: "Spring-Winter" },
  ];
  localStorage.setItem("category", JSON.stringify(category));
}

// ================= PRODUCTS =================
if (!localStorage.getItem("products")) {
  const products = [
    {
      id: "P001",
      name: "Tiered Gown with Graphic Ribbon Print",
      type: "Women",
      cate: "Dresses",
      collection: "none",
      costPrice: 200000,
      profitPercent: 25,
      price: 250000,
      color: ["blue", "black"],
      productDesc:
        "A silk halter-neck dress or jumpsuit featuring a tied bow at the neck and a vibrant, graphic black-and-white print resembling swirling ribbons. The garment is designed in several tiered layers on the bodice and skirt/trousers, giving it volume and dynamic movement on the runway.",
      images: [
        "./assets/img/Womenfashion/Dresses/1.1.webp",
        "./assets/img/Womenfashion/Dresses/1.2.webp",
        "./assets/img/Womenfashion/Dresses/1.3.webp",
      ],
      sizes: ["M", "L", "XL"],
      quantity: 10,
      hidden: false,
    },
    {
      id: "P002",
      name: ". Mid-Length Flared Dress with Belt",
      type: "Women",
      cate: "Dresses",
      collection: "none",
      costPrice: 180000,
      profitPercent: 30,
      price: 234000,
      color: ["white", "black"],
      productDesc:
        "A hallmark Dior silhouette, the mid-length dress celebrates the House's tailoring spirit. Crafted in white lightweight wool and silk shantung, it features an elegant, flared cut enhanced by a tonal belt highlighting the waist as well as by a tonal covered-button closure. Completed by piped pockets on the front, the dress will create a couture look.",
      images: [
        "./assets/img/Womenfashion/Dresses/2.1.webp",
        "./assets/img/Womenfashion/Dresses/2.2.webp",
        "./assets/img/Womenfashion/Dresses/2.3.webp",
      ],
      sizes: ["M", "L", "XL"],
      quantity: 10,
      hidden: false,
    },
    {
      id: "P003",
      name: ". Ruffled Crop Jacket and Black Jacquard Jumpsuit",
      type: "Women",
      cate: "Dresses",
      collection: "none",
      costPrice: 280000,
      profitPercent: 25,
      price: 350000,
      color: ["blue", "white"],
      productDesc:
        "A striking contrast between outerwear and the base layer. The look features a romantic, cropped ivory jacket with voluminous sleeves and dramatic layered ruffles around the collar. The garment underneath is a black jumpsuit or co-ord set (corset/vest and wide-leg trousers) featuring a subtle jacquard pattern, cinched at the waist with a delicate ribbon bow.",
      images: [
        "./assets/img/Womenfashion/Dresses/3.1.webp",
        "./assets/img/Womenfashion/Dresses/3.2.webp",
      ],
      sizes: ["M", "L", "XL"],
      quantity: 8,
      hidden: false,
    },
    {
      id: "P004",
      name: "Mid-Length Belted Shirtdress",
      type: "Women",
      cate: "Dresses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The mid-length shirtdress showcases a multicolor Butterflies & Iris motif, showcasing a soft watercolor effect suggesting an unfinished sketch, in a nod to the artistic spirit of the collection. Made in beige cotton and silk poplin, it stands out with an elegant flared silhouette and tonal belt highlighting the waist. Completed by cap sleeves, the dress can be paired with other Butterflies & Iris creations for a signature look.",
      images: [
        "./assets/img/Womenfashion/Dresses/4.1.webp",
        "./assets/img/Womenfashion/Dresses/4.2.webp",
        "./assets/img/Womenfashion/Dresses/4.3.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P005",
      name: "Mid-Length Flared Dress with Removable Ruched Collar",
      type: "Women",
      cate: "Dresses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The mid-length dress is a sophisticated and iconic Dior silhouette. Crafted in black silk faille, it features a flared cut enhanced by the collection's hallmark removable ruched collar, as well as ruffled cap sleeves. The dress will create a feminine and elegant look.",
      images: [
        "./assets/img/Womenfashion/Dresses/5.1.jpg",
        "./assets/img/Womenfashion/Dresses/5.2.jpg",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P006",
      name: "Flared Dress",
      type: "Women",
      cate: "Dresses",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The mid-length dress, a hallmark Dior silhouette, is a sophisticated and modern design. Crafted in red wool and silk shantung, it features an elegant flared cut enhanced by a square neckline and a waistband adorned with a large bow in the back. The mid-length dress will create a couture look",
      images: [
        "./assets/img/Womenfashion/Dresses/6.1.webp",
        "./assets/img/Womenfashion/Dresses/6.2.webp",
        "./assets/img/Womenfashion/Dresses/6.3.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P007",
      name: "Sleeveless Top",
      type: "Women",
      cate: "Tops-Blouses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The top showcases a timeless couture look. Made in finely knit black virgin wool, it is distinguished by a regular-fit silhouette enhanced by ruffled detailing highlighting the armholes, as well as the collection's hallmark removable ruched collar. The top can be paired with any of the season's looks",
      images: [
        "./assets/img/Womenfashion/Tops-Blouses/1.1.webp",
        "./assets/img/Womenfashion/Tops-Blouses/1.2.webp",
        "./assets/img/Womenfashion/Tops-Blouses/1.3.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P008",
      name: "Fleece top",
      type: "Women",
      cate: "Tops-Blouses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "Fleece, a fabric with a contemporary, lifestyle character, defines this top with stand-up collar and front zipper closure. The embroidered logo and cropped fit add an iconic touch to the garment, perfect for bold combinations when mixed with classic elements.",
      images: [
        "./assets/img/Womenfashion/Tops-Blouses/2.1.avif",
        "./assets/img/Womenfashion/Tops-Blouses/2.2.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P009",
      name: "Poplin top",
      type: "Women",
      cate: "Tops-Blouses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "A delicate stripe pattern and playful references to scout imagery define the spirit of this poplin top. The cropped fit and detachable scarf lend versatility and character, encouraging personal styling interpretations.",
      images: [
        "./assets/img/Womenfashion/Tops-Blouses/3.1.avif",
        "./assets/img/Womenfashion/Tops-Blouses/3.2.avif",
        "./assets/img/Womenfashion/Tops-Blouses/3.3.avif",
        "./assets/img/Womenfashion/Tops-Blouses/3.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P010",
      name: "Poplin shirt",
      type: "Women",
      cate: "Tops-Blouses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The classic men’s shirt is reinterpreted in this poplin version with a slightly cropped fit, enriched by detachable collar and cuffs that add character and versatility to a Miu Miu wardrobe icon.",
      images: [
        "./assets/img/Womenfashion/Tops-Blouses/4.1.avif",
        "./assets/img/Womenfashion/Tops-Blouses/4.2.webp",
        "./assets/img/Womenfashion/Tops-Blouses/4.3.avif",
        "./assets/img/Womenfashion/Tops-Blouses/4.4.avif",
        "./assets/img/Womenfashion/Tops-Blouses/4.5.avif",
        "./assets/img/Womenfashion/Tops-Blouses/4.6.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P011",
      name: "Cotton piqué polo shirt",
      type: "Women",
      cate: "Tops-Blouses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The casual style of the polo shirt meets Miu Miu's distinctive character in this cotton piqué polo shirt. The embroidered logo completes the design.",
      images: [
        "./assets/img/Womenfashion/Tops-Blouses/5.1.avif",
        "./assets/img/Womenfashion/Tops-Blouses/5.2.avif",
        "./assets/img/Womenfashion/Tops-Blouses/5.3.avif",
        "./assets/img/Womenfashion/Tops-Blouses/5.4.avif",
        "./assets/img/Womenfashion/Tops-Blouses/5.5.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P012",
      name: "Cherry Bow Cropped Tee",
      type: "Women",
      cate: "Tops-Blouses",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "Cropped and relaxed for that effortless summer vibe. Featuring a sweet cherry print and bow-tie sleeves, this playful tee pairs perfectly with jeans or flowy skirts for a cute and comfy look.",
      images: [
        "./assets/img/Womenfashion/Tops-Blouses/6.1.webp",
        "./assets/img/Womenfashion/Tops-Blouses/6.2.webp",
        "./assets/img/Womenfashion/Tops-Blouses/6.3.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P0013",
      name: "Chevron miniskirt",
      type: "Women",
      cate: "Bottoms",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The sporty essence of the Miu Miu wardrobe is reinterpreted through classic fabrics. This chevron skirt stands out for its mini silhouette and soft line defined by the drawstring waist, an element of experimentation and contemporary versatility.",
      images: [
        "./assets/img/Womenfashion/Bottoms/1.1.avif",
        "./assets/img/Womenfashion/Bottoms/1.2.avif",
        "./assets/img/Womenfashion/Bottoms/1.3.avif",
        "./assets/img/Womenfashion/Bottoms/1.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P014",
      name: "Ruffle Hem Denim Pants",
      type: "Women",
      cate: "Bottoms",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "A twist on classic denim — ruffle hems bring soft femininity to everyday jeans. With a slight flare at the hem, these pants flatter your legs and elevate your casual look with a French-inspired flair.",
      images: [
        "./assets/img/Womenfashion/Bottoms/2.1.webp",
        "./assets/img/Womenfashion/Bottoms/2.2.webp",
        "./assets/img/Womenfashion/Bottoms/2.3.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P015",
      name: "Rosette Bubble Mini Skirt",
      type: "Women",
      cate: "Bottoms",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "Sweet but never subtle — this skirt is for the bold. With 3D rosette texture and a voluminous bubble silhouette, it’s your perfect match for bikinis, crop tops, and all things hot girl summer.",
      images: [
        "./assets/img/Womenfashion/Bottoms/3.1.webp",
        "./assets/img/Womenfashion/Bottoms/3.2.webp",
        "./assets/img/Womenfashion/Bottoms/3.3.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P016",
      name: "Washed flocked chambray pants",
      type: "Women",
      cate: "Bottoms",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The soft velvety effect of flocked chambray enhances the wide-legged cut of these pants, while the garment-washed treatment accentuates the versatility of this reinterpreted classic. ",
      images: [
        "./assets/img/Womenfashion/Bottoms/4.1.avif",
        "./assets/img/Womenfashion/Bottoms/4.2.avif",
        "./assets/img/Womenfashion/Bottoms/4.3.avif",
        "./assets/img/Womenfashion/Bottoms/4.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P017",
      name: "Denim miniskirt",
      type: "Women",
      cate: "Bottoms",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The timeless character of denim meets Miu Miu's effortless femininity in this miniskirt. The embroidered logo on the back patch pocket adds an iconic touch to the garment while the hem with exposed pocket lining suggests a construction process that underlines the spontaneity of these actions.",
      images: [
        "./assets/img/Womenfashion/Bottoms/5.1.avif",
        "./assets/img/Womenfashion/Bottoms/5.2.avif",
        "./assets/img/Womenfashion/Bottoms/5.3.avif",
        "./assets/img/Womenfashion/Bottoms/5.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P018",
      name: "Twinset",
      type: "Women",
      cate: "Outerwear",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The twinset is both modern and timeless. Crafted in a light pink cashmere knit, it is composed of a round neck tank top and cardigan showcasing star buttons. The twinset will complete a skirt from the collection for a hallmark look.",
      images: [
        "./assets/img/Womenfashion/Outerwear/1.1.webp",
        "./assets/img/Womenfashion/Outerwear/1.2.webp",
        "./assets/img/Womenfashion/Outerwear/1.3.webp",
        "./assets/img/Womenfashion/Outerwear/1.4.webp",
        "./assets/img/Womenfashion/Outerwear/1.5.jpg",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P019",
      name: "Embroidered Sweater",
      type: "Women",
      cate: "Outerwear",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The embroidered sweater features a multicolor Butterflies & Iris motif, showcasing a soft watercolor effect suggesting an unfinished sketch, enhanced by three-dimensional butterflies. Crafted in a white alpaca, cashmere and silk knit, it features a regular-fit silhouette embellished with the Christian Dior Paris signature on the back as well as ribbed trim. The sweater can be styled with other Butterflies & Iris creations to complete the look.",
      images: [
        "./assets/img/Womenfashion/Outerwear/2.1.webp",
        "./assets/img/Womenfashion/Outerwear/2.2.webp",
        "./assets/img/Womenfashion/Outerwear/2.3.jpg",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P020",
      name: "Macrocannage Regular-Fit Jacket",
      type: "Women",
      cate: "Outerwear",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "Combining modernity and elegance, the jacket showcases the hallmark Macrocannage motif. Crafted in a black and white cotton-blend tweed knit with a textured effect, it features a regular-fit silhouette, elevated by a fringed hem and cuffs, as well as a button closure adorned with black CD Dior Tribales buttons, inspired by the House's iconic earring. Highlighted at the waist by large patch pockets, the jacket will pair well with the matching shorts to complete the look.",
      images: [
        "./assets/img/Womenfashion/Outerwear/3.1.jpg",
        "./assets/img/Womenfashion/Outerwear/3.2.webp",
        "./assets/img/Womenfashion/Outerwear/3.3.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P021",
      name: "Montaigne Bar Jacket",
      type: "Women",
      cate: "Outerwear",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The 30 Montaigne Bar jacket is an emblematic piece from the New Look collection, first created by Christian Dior in 1947. Crafted in a lightweight blend of white wool and silk, it features a notched collar and slit pockets that delicately highlight the waist. The Bar jacket will pair well with the entire Dior wardrobe for an elegant and refined silhouette.",
      images: [
        "./assets/img/Womenfashion/Outerwear/4.1.webp",
        "./assets/img/Womenfashion/Outerwear/4.2.webp",
        "./assets/img/Womenfashion/Outerwear/4.3.webp",
        "./assets/img/Womenfashion/Outerwear/4.4.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P022",
      name: "Prince of Wales checked wool jacket",
      type: "Women",
      cate: "Outerwear",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Prince of Wales check defines the sartorial character of this single-breasted jacket, while the straight fit and embroidered logo add a touch of boldness and style to this reinterpretation of a classic menswear piece.",
      images: [
        "./assets/img/Womenfashion/Outerwear/5.1.avif",
        "./assets/img/Womenfashion/Outerwear/5.2.avif",
        "./assets/img/Womenfashion/Outerwear/5.3.avif",
        "./assets/img/Womenfashion/Outerwear/5.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P023",
      name: "Poplin blouson jacket",
      type: "Women",
      cate: "Outerwear",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The iconic button-down poplin shirt is reinterpreted in this blouson jacket with a fresh, new essence made unique by the button detail on the back that plays with the world of men's shirts.",
      images: [
        "./assets/img/Womenfashion/Outerwear/6.1.avif",
        "./assets/img/Womenfashion/Outerwear/6.2.avif",
        "./assets/img/Womenfashion/Outerwear/6.3.avif",
        "./assets/img/Womenfashion/Outerwear/6.4.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P024",
      name: "Banana Raglan Oversized T-shirt",
      type: "Men",
      cate: "T-Shirts-Polos",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Banana Raglan Oversized T-shirt is a comfortable and stylish choice for casual wear. Made from soft cotton fabric, it features a relaxed fit and raglan sleeves for ease of movement.",
      images: [
        "./assets/img/MenFashion/T-Shirts-Polos/1.1.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/1.2.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/1.3.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/1.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P025",
      name: "Tape Type Tr T-shirt",
      type: "Men",
      cate: "T-Shirts-Polos",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Tape Type Tr T-shirt is a modern and stylish choice for casual wear. Made from high-quality cotton fabric, it features a comfortable fit and trendy tape detailing on the sleeves.",
      images: [
        "./assets/img/MenFashion/T-Shirts-Polos/2.1.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/2.2.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/2.3.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/2.4.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/2.5.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/2.6.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/2.7.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/2.8.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P026",
      name: "Back T-shirt Medium",
      type: "Men",
      cate: "T-Shirts-Polos",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Back T-shirt Medium is a comfortable and stylish choice for casual wear. Made from soft cotton fabric, it features a relaxed fit and a classic crew neckline.",
      images: [
        "./assets/img/MenFashion/T-Shirts-Polos/3.1.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/3.2.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/3.3.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/3.4.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/3.5.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P028",
      name: "Diy Imprint Cropped",
      type: "Men",
      cate: "T-Shirts-Polos",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Diy Imprint Cropped T-shirt is a trendy and stylish choice for casual wear. Made from soft cotton fabric, it features a relaxed fit and a unique cropped design.",
      images: [
        "./assets/img/MenFashion/T-Shirts-Polos/4.1.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/4.2.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/4.3.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/4.4.avif",
        "./assets/img/MenFashion/T-Shirts-Polos/4.5.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P029",
      name: "Cotton Piqué Polo Shirt With Vlogo Patch",
      type: "Men",
      cate: "T-Shirts-Polos",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Cotton Piqué Polo Shirt With Vlogo Patch is a stylish and comfortable choice for casual wear. Made from high-quality cotton fabric, it features a classic polo design with a Vlogo patch on the chest.",
      images: [
        "./assets/img/MenFashion/T-Shirts-Polos/5.1.webp",
        "./assets/img/MenFashion/T-Shirts-Polos/5.2.webp",
        "./assets/img/MenFashion/T-Shirts-Polos/5.3.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P030",
      name: "Regular Fit Cotton Poplin Shirt",
      type: "Men",
      cate: "Shirts",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "A long-sleeved shirt in cotton poplin, cut to a regular fit. The style is embroidered with a tonal Equestrian Knight Design and our logo. Fold back the cuffs to reveal the Burberry Check lining in signature sand beige.",
      images: [
        "./assets/img/MenFashion/Shirts/1.1.webp",
        "./assets/img/MenFashion/Shirts/1.2.webp",
        "./assets/img/MenFashion/Shirts/1.3.webp",
        "./assets/img/MenFashion/Shirts/1.4.webp",
        "./assets/img/MenFashion/Shirts/1.5.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P031",
      name: "Striped Cotton Shirt With Ruffles",
      type: "Men",
      cate: "Shirts",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Striped Cotton Shirt With Ruffles is a stylish and comfortable choice for casual wear. Made from high-quality cotton fabric, it features a classic striped design with ruffle detailing.",
      images: [
        "./assets/img/MenFashion/Shirts/2.1.webp",
        "./assets/img/MenFashion/Shirts/2.2.webp",
        "./assets/img/MenFashion/Shirts/2.3.webp",
        "./assets/img/MenFashion/Shirts/2.4.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P032",
      name: "MonCotton Poplin Bowling Shirt With Cherryfic Printtaigne",
      type: "Men",
      cate: "Shirts",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The MonCotton Poplin Bowling Shirt With Cherryfic Printtaigne is a stylish and comfortable choice for casual wear. Made from high-quality cotton fabric, it features a unique cherry print design.",
      images: [
        "./assets/img/MenFashion/Shirts/3.1.webp",
        "./assets/img/MenFashion/Shirts/3.2.webp",
        "./assets/img/MenFashion/Shirts/3.3.webp",
        "./assets/img/MenFashion/Shirts/3.4.webp",
        "./assets/img/MenFashion/Shirts/3.5.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P033",
      name: "Relaxed Fit Check Cotton Shirt",
      type: "Men",
      cate: "Shirts",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Relaxed Fit Check Cotton Shirt is a stylish and comfortable choice for casual wear. Made from high-quality cotton fabric, it features a classic check pattern.",
      images: [
        "./assets/img/MenFashion/Shirts/4.1.webp",
        "./assets/img/MenFashion/Shirts/4.2.webp",
        "./assets/img/MenFashion/Shirts/4.3.webp",
        "./assets/img/MenFashion/Shirts/4.4.webp",
        "./assets/img/MenFashion/Shirts/4.5.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P034",
      name: "Trouser",
      type: "Men",
      cate: "Pants-Trousers",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Trouser is a stylish and comfortable choice for casual wear. Made from high-quality fabric, it features a classic design.",
      images: [
        "./assets/img/MenFashion/Pants-Trousers/1.1.avif",
        "./assets/img/MenFashion/Pants-Trousers/1.2.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P035",
      name: "Banana Baggy Pants",
      type: "Men",
      cate: "Pants-Trousers",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Banana Baggy Pants are a stylish and comfortable choice for casual wear. Made from high-quality fabric, they feature a relaxed fit and trendy design.",
      images: [
        "./assets/img/MenFashion/Pants-Trousers/2.1.avif",
        "./assets/img/MenFashion/Pants-Trousers/2.2.avif",
        "./assets/img/MenFashion/Pants-Trousers/2.3.avif",
        "./assets/img/MenFashion/Pants-Trousers/2.4.avif",
        "./assets/img/MenFashion/Pants-Trousers/2.5.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P036",
      name: "Trouser Monogram",
      type: "Men",
      cate: "Pants-Trousers",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The trendy trousers impress with the LV Camo pattern interwoven with many delicate Monogram motifs. Made from Ripstop fabric woven from organic cotton, the design has many convenient pockets and patch details at the front of the knee, embellished with the brand's signature Marque L.Vuitton Déposée leather label on the left box pocket.",
      images: [
        "./assets/img/MenFashion/Pants-Trousers/3.1.avif",
        "./assets/img/MenFashion/Pants-Trousers/3.2.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P037",
      name: "Relaxed Fit Pants in Blue",
      type: "Men",
      cate: "Pants-Trousers",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Relaxed Fit Pants in Blue are a stylish and comfortable choice for casual wear. Made from high-quality fabric, they feature a relaxed fit and trendy design.",
      images: [
        "./assets/img/MenFashion/Pants-Trousers/4.1.avif",
        "./assets/img/MenFashion/Pants-Trousers/4.2.avif",
        "./assets/img/MenFashion/Pants-Trousers/4.3.avif",
        "./assets/img/MenFashion/Pants-Trousers/4.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P038",
      name: "Distressed Large Cargo Pants",
      type: "Men",
      cate: "Pants-Trousers",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Distressed Large Cargo Pants are a stylish and functional choice for casual wear. Made from high-quality fabric, they feature a relaxed fit and multiple pockets for convenience.",
      images: [
        "./assets/img/MenFashion/Pants-Trousers/5.1.avif",
        "./assets/img/MenFashion/Pants-Trousers/5.2.avif",
        "./assets/img/MenFashion/Pants-Trousers/5.3.avif",
        "./assets/img/MenFashion/Pants-Trousers/5.4.avif",
        "./assets/img/MenFashion/Pants-Trousers/5.5.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P039",
      name: "Short Malletier",
      type: "Men",
      cate: "Shorts",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Short Malletier shorts are a stylish and comfortable choice for casual wear. Made from high-quality fabric, they feature a relaxed fit and trendy design.",
      images: [
        "./assets/img/MenFashion/Shorts/1.1.avif",
        "./assets/img/MenFashion/Shorts/1.2.avif",
        "./assets/img/MenFashion/Shorts/1.3.avif",
        "./assets/img/MenFashion/Shorts/1.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P040",
      name: "Balenciaga Back Shorts",
      type: "Men",
      cate: "Shorts",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Balenciaga Back Shorts are a stylish and comfortable choice for casual wear. Made from high-quality fabric, they feature a relaxed fit and trendy design.",
      images: [
        "./assets/img/MenFashion/Shorts/2.1.avif",
        "./assets/img/MenFashion/Shorts/2.2.avif",
        "./assets/img/MenFashion/Shorts/2.3.avif",
        "./assets/img/MenFashion/Shorts/2.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P041",
      name: "Basketball Sweat Shorts",
      type: "Men",
      cate: "Shorts",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Basketball Sweat Shorts are a stylish and comfortable choice for casual wear. Made from high-quality fabric, they feature a relaxed fit and trendy design.",
      images: [
        "./assets/img/MenFashion/Shorts/3.1.avif",
        "./assets/img/MenFashion/Shorts/3.2.avif",
        "./assets/img/MenFashion/Shorts/3.3.avif",
        "./assets/img/MenFashion/Shorts/3.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P042",
      name: "Cotton Popeline Bermuda Shorts With Toute La V Print",
      type: "Men",
      cate: "Shorts",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Cotton Popeline Bermuda Shorts With Toute La V Print are a stylish and comfortable choice for casual wear. Made from high-quality fabric, they feature a relaxed fit and trendy design.",
      images: [
        "./assets/img/MenFashion/Shorts/4.1.webp",
        "./assets/img/MenFashion/Shorts/4.2.webp",
        "./assets/img/MenFashion/Shorts/4.3.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P043",
      name: "Blouson",
      type: "Men",
      cate: "Outerwear",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Blouson is a stylish and comfortable choice for casual wear. Made from high-quality fabric, it features a relaxed fit and trendy design.",
      images: [
        "./assets/img/MenFashion/Outerwear/1.1.avif",
        "./assets/img/MenFashion/Outerwear/1.2.avif",
        "./assets/img/MenFashion/Outerwear/1.3.avif",
        "./assets/img/MenFashion/Outerwear/1.4.avif",
        "./assets/img/MenFashion/Outerwear/1.5.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P044",
      name: "Bomber Jacket Large Fit",
      type: "Men",
      cate: "Outerwear",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Bomber Jacket Large Fit is a stylish and comfortable choice for casual wear. Made from high-quality fabric, it features a relaxed fit and trendy design.",
      images: [
        "./assets/img/MenFashion/Outerwear/2.1.avif",
        "./assets/img/MenFashion/Outerwear/2.2.avif",
        "./assets/img/MenFashion/Outerwear/2.3.avif",
        "./assets/img/MenFashion/Outerwear/2.4.avif",
        "./assets/img/MenFashion/Outerwear/2.5.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P045",
      name: "Tracksuit Jacket",
      type: "Men",
      cate: "Outerwear",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Tracksuit Jacket is a stylish and comfortable choice for casual wear. Made from high-quality fabric, it features a relaxed fit and trendy design.",
      images: [
        "./assets/img/MenFashion/Outerwear/3.1.avif",
        "./assets/img/MenFashion/Outerwear/3.2.avif",
        "./assets/img/MenFashion/Outerwear/3.3.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P046",
      name: "Security Tape Logo Large Zip-up Hoodie",
      type: "Men",
      cate: "Outerwear",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Security Tape Logo Large Zip-up Hoodie is a stylish and comfortable choice for casual wear. Made from high-quality fabric, it features a relaxed fit and trendy design.",
      images: [
        "./assets/img/MenFashion/Outerwear/4.1.avif",
        "./assets/img/MenFashion/Outerwear/4.2.avif",
        "./assets/img/MenFashion/Outerwear/4.3.avif",
        "./assets/img/MenFashion/Outerwear/4.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P047",
      name: "City Of Angels Hoodie Medium Fit",
      type: "Men",
      cate: "Outerwear",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The City Of Angels Hoodie Medium Fit is a stylish and comfortable choice for casual wear. Made from high-quality fabric, it features a relaxed fit and trendy design.",
      images: [
        "./assets/img/MenFashion/Outerwear/5.1.avif",
        "./assets/img/MenFashion/Outerwear/5.2.avif",
        "./assets/img/MenFashion/Outerwear/5.3.avif",
        "./assets/img/MenFashion/Outerwear/5.4.avif",
        "./assets/img/MenFashion/Outerwear/5.5.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P048",
      name: "Back Hoodie Medium Fit",
      type: "Men",
      cate: "Outerwear",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Back Hoodie Medium Fit is a stylish and comfortable choice for casual wear. Made from high-quality fabric, it features a relaxed fit and trendy design.",
      images: [
        "./assets/img/MenFashion/Outerwear/6.1.avif",
        "./assets/img/MenFashion/Outerwear/6.2.avif",
        "./assets/img/MenFashion/Outerwear/6.3.avif",
        "./assets/img/MenFashion/Outerwear/6.4.avif",
        "./assets/img/MenFashion/Outerwear/6.5.avif",
        "./assets/img/MenFashion/Outerwear/6.6.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P049",
      name: "Vedette sunglasses",
      type: "Accessories",
      cate: "Sunglasses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Vedette sunglasses, unveiled at the FW25 show, draw inspiration from the early 2000s and combine a narrow rectangular frame with tall temples. The lenses, marked with the Miu Miu logo, add a bold and glamorous touch that invites instant wear.",
      images: [
        "./assets/img/Accessories/Sunglasses/1.1.avif",
        "./assets/img/Accessories/Sunglasses/1.2.avif",
        "./assets/img/Accessories/Sunglasses/1.3.avif",
        "./assets/img/Accessories/Sunglasses/1.4.avif",
        "./assets/img/Accessories/Sunglasses/1.5.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P050",
      name: "Miu Regard sunglasses",
      type: "Accessories",
      cate: "Sunglasses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Miu Regard sunglasses are a chic accessory that combines modern design with classic elegance. Featuring a bold frame and high-quality lenses, they offer both style and protection from the sun.",
      images: [
        "./assets/img/Accessories/Sunglasses/2.1.avif",
        "./assets/img/Accessories/Sunglasses/2.2.avif",
        "./assets/img/Accessories/Sunglasses/2.3.avif",
        "./assets/img/Accessories/Sunglasses/2.4.avif",
        "./assets/img/Accessories/Sunglasses/2.5.avif",
        "./assets/img/Accessories/Sunglasses/2.6.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P051",
      name: "Miu Miu Logo sunglasses",
      type: "Accessories",
      cate: "Sunglasses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Miu Miu Logo sunglasses are a stylish accessory that combines modern design with classic elegance. Featuring a bold frame and high-quality lenses, they offer both style and protection from the sun.",
      images: [
        "./assets/img/Accessories/Sunglasses/3.1.avif",
        "./assets/img/Accessories/Sunglasses/3.2.avif",
        "./assets/img/Accessories/Sunglasses/3.3.avif",
        "./assets/img/Accessories/Sunglasses/3.4.avif",
        "./assets/img/Accessories/Sunglasses/3.5.avif",
        "./assets/img/Accessories/Sunglasses/3.6.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P052",
      name: "Miu Miu Logo sunglasses",
      type: "Accessories",
      cate: "Sunglasses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Miu Miu Logo sunglasses are a stylish accessory that combines modern design with classic elegance. Featuring a bold frame and high-quality lenses, they offer both style and protection from the sun.",
      images: [
        "./assets/img/Accessories/Sunglasses/4.1.avif",
        "./assets/img/Accessories/Sunglasses/4.2.avif",
        "./assets/img/Accessories/Sunglasses/4.3.avif",
        "./assets/img/Accessories/Sunglasses/4.4.avif",
        "./assets/img/Accessories/Sunglasses/4.5.avif",
        "./assets/img/Accessories/Sunglasses/4.6.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P053",
      name: "MiniCD S1I",
      type: "Accessories",
      cate: "Sunglasses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The MiniCD S1I sunglasses are a stylish accessory that combines modern design with classic elegance. Featuring a bold frame and high-quality lenses, they offer both style and protection from the sun.",
      images: [
        "./assets/img/Accessories/Sunglasses/5.1.webp",
        "./assets/img/Accessories/Sunglasses/5.2.webp",
        "./assets/img/Accessories/Sunglasses/5.3.webp",
        "./assets/img/Accessories/Sunglasses/5.4.webp",
        "./assets/img/Accessories/Sunglasses/5.5.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P054",
      name: "Pocket nappa leather bag",
      type: "Accessories",
      cate: "Bags-Purses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Pocket nappa leather bag is a stylish and functional accessory that combines modern design with classic elegance. Made from high-quality nappa leather, it offers both durability and sophistication.",
      images: [
        "./assets/img/Accessories/Bags_Purses/1.1.avif",
        "./assets/img/Accessories/Bags_Purses/1.2.avif",
        "./assets/img/Accessories/Bags_Purses/1.3.avif",
        "./assets/img/Accessories/Bags_Purses/1.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P055",
      name: "Wander matelassé suede bag",
      type: "Accessories",
      cate: "Bags-Purses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Wander matelassé suede bag is a stylish and functional accessory that combines modern design with classic elegance. Made from high-quality suede, it offers both durability and sophistication.",
      images: [
        "./assets/img/Accessories/Bags_Purses/2.1.avif",
        "./assets/img/Accessories/Bags_Purses/2.2.avif",
        "./assets/img/Accessories/Bags_Purses/2.3.avif",
        "./assets/img/Accessories/Bags_Purses/2.4.avif",
        "./assets/img/Accessories/Bags_Purses/2.5.avif",
        "./assets/img/Accessories/Bags_Purses/2.6.avif",
        "./assets/img/Accessories/Bags_Purses/2.7.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P056",
      name: "Mini Lady Dior Bag",
      type: "Accessories",
      cate: "Bags-Purses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Mini Lady Dior Bag is a stylish and functional accessory that combines modern design with classic elegance. Made from high-quality materials, it offers both durability and sophistication.",
      images: [
        "./assets/img/Accessories/Bags_Purses/3.1.webp",
        "./assets/img/Accessories/Bags_Purses/3.2.webp",
        "./assets/img/Accessories/Bags_Purses/3.3.webp",
        "./assets/img/Accessories/Bags_Purses/3.4.webp",
        "./assets/img/Accessories/Bags_Purses/3.5.webp",
        "./assets/img/Accessories/Bags_Purses/3.6.webp",
        "./assets/img/Accessories/Bags_Purses/3.7.webp",
        "./assets/img/Accessories/Bags_Purses/3.8.webp",
        "./assets/img/Accessories/Bags_Purses/3.9.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P057",
      name: "Saddle Bag with Strap",
      type: "Accessories",
      cate: "Bags-Purses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Saddle Bag with Strap is a stylish and functional accessory that combines modern design with classic elegance. Made from high-quality materials, it offers both durability and sophistication.",
      images: [
        "./assets/img/Accessories/Bags_Purses/4.1.webp",
        "./assets/img/Accessories/Bags_Purses/4.2.webp",
        "./assets/img/Accessories/Bags_Purses/4.3.webp",
        "./assets/img/Accessories/Bags_Purses/4.4.webp",
        "./assets/img/Accessories/Bags_Purses/4.5.webp",
        "./assets/img/Accessories/Bags_Purses/4.6.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P058",
      name: "Saddle Bag with Strap",
      type: "Accessories",
      cate: "Bags-Purses",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Saddle Bag with Strap is a stylish and functional accessory that combines modern design with classic elegance. Made from high-quality materials, it offers both durability and sophistication.",
      images: [
        "./assets/img/Accessories/Bags_Purses/5.1.webp",
        "./assets/img/Accessories/Bags_Purses/5.2.webp",
        "./assets/img/Accessories/Bags_Purses/5.3.webp",
        "./assets/img/Accessories/Bags_Purses/5.4.webp",
        "./assets/img/Accessories/Bags_Purses/5.5.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P059",
      name: "Logo necklace",
      type: "Accessories",
      cate: "Jewelry",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Logo necklace is a stylish accessory that adds a touch of elegance to any outfit. Made from high-quality materials, it features a delicate chain and a pendant with the brand's iconic logo.",
      images: [
        "./assets/img/Accessories/Jewelry/1.1.avif",
        "./assets/img/Accessories/Jewelry/1.2.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P060",
      name: "Metal and leather necklace",
      type: "Accessories",
      cate: "Jewelry",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Metal and leather necklace is a stylish accessory that adds a touch of elegance to any outfit. Made from high-quality materials, it features a delicate chain and a pendant with the brand's iconic logo.",
      images: [
        "./assets/img/Accessories/Jewelry/2.1.avif",
        "./assets/img/Accessories/Jewelry/2.2.avif",
        "./assets/img/Accessories/Jewelry/2.3.avif",
        "./assets/img/Accessories/Jewelry/2.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P061",
      name: "Metal necklace with synthetic pearls",
      type: "Accessories",
      cate: "Jewelry",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Metal necklace with synthetic pearls is a stylish accessory that adds a touch of elegance to any outfit. Made from high-quality materials, it features a delicate chain and a pendant with the brand's iconic logo.",
      images: [
        "./assets/img/Accessories/Jewelry/3.1.avif",
        "./assets/img/Accessories/Jewelry/3.2.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P062",
      name: "Metal necklace",
      type: "Accessories",
      cate: "Jewelry",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Metal necklace is a stylish accessory that adds a touch of elegance to any outfit. Made from high-quality materials, it features a delicate chain and a pendant with the brand's iconic logo.",
      images: [
        "./assets/img/Accessories/Jewelry/4.1.avif",
        "./assets/img/Accessories/Jewelry/4.2.avif",
        "./assets/img/Accessories/Jewelry/4.3.avif",
        "./assets/img/Accessories/Jewelry/4.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P063",
      name: "Leather choker",
      type: "Accessories",
      cate: "Jewelry",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Leather choker is a stylish accessory that adds a touch of elegance to any outfit. Made from high-quality materials, it features a delicate chain and a pendant with the brand's iconic logo.",
      images: [
        "./assets/img/Accessories/Jewelry/5.1.avif",
        "./assets/img/Accessories/Jewelry/5.2.avif",
        "./assets/img/Accessories/Jewelry/5.3.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P064",
      name: "Metal bow earrings",
      type: "Accessories",
      cate: "Jewelry",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Metal bow earrings are a stylish accessory that adds a touch of elegance to any outfit. Made from high-quality materials, they feature a delicate design with the brand's iconic logo.",
      images: [
        "./assets/img/Accessories/Jewelry/6.1.avif",
        "./assets/img/Accessories/Jewelry/6.2.avif",
        "./assets/img/Accessories/Jewelry/6.3.avif",
        "./assets/img/Accessories/Jewelry/6.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P065",
      name: "Metal bow earrings",
      type: "Accessories",
      cate: "Jewelry",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Metal bow earrings are a stylish accessory that adds a touch of elegance to any outfit. Made from high-quality materials, they feature a delicate design with the brand's iconic logo.",
      images: [
        "./assets/img/Accessories/Jewelry/7.1.avif",
        "./assets/img/Accessories/Jewelry/7.2.avif",
        "./assets/img/Accessories/Jewelry/7.3.avif",
        "./assets/img/Accessories/Jewelry/7.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P066",
      name: "Metal brooch with crystals",
      type: "Accessories",
      cate: "Jewelry",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Metal brooch with crystals is a stunning accessory that adds a touch of glamour to any outfit. Made from high-quality materials, it features a beautiful design adorned with sparkling crystals.",
      images: [
        "./assets/img/Accessories/Jewelry/8.1.avif",
        "./assets/img/Accessories/Jewelry/8.2.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P067",
      name: "Felt hat",
      type: "Accessories",
      cate: "Hats-Caps",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Felt hat is a stylish accessory that adds a touch of elegance to any outfit. Made from high-quality materials, it features a classic design that never goes out of style.",
      images: [
        "./assets/img/Accessories/Hats_Caps/1.1.avif",
        "./assets/img/Accessories/Hats_Caps/1.2.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P068",
      name: "Printed leather cowboy hat",
      type: "Accessories",
      cate: "Hats-Caps",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Printed leather cowboy hat is a stylish accessory that adds a touch of rugged charm to any outfit. Made from high-quality materials, it features a classic cowboy design with a modern twist.",
      images: [
        "./assets/img/Accessories/Hats_Caps/2.1.avif",
        "./assets/img/Accessories/Hats_Caps/2.2.avif",
        "./assets/img/Accessories/Hats_Caps/2.3.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P069",
      name: "Velvet baseball cap",
      type: "Accessories",
      cate: "Hats-Caps",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Velvet baseball cap is a stylish accessory that adds a touch of casual elegance to any outfit. Made from high-quality materials, it features a classic design with a modern twist.",
      images: [
        "./assets/img/Accessories/Hats_Caps/3.1.avif",
        "./assets/img/Accessories/Hats_Caps/3.2.avif",
        "./assets/img/Accessories/Hats_Caps/3.3.avif",
        "./assets/img/Accessories/Hats_Caps/3.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P070",
      name: "Basketball Cap",
      type: "Accessories",
      cate: "Hats-Caps",
      collection: "none",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Basketball Cap is a stylish accessory that adds a touch of sporty elegance to any outfit. Made from high-quality materials, it features a classic design with a modern twist.",
      images: [
        "./assets/img/Accessories/Hats_Caps/4.1.avif",
        "./assets/img/Accessories/Hats_Caps/4.2.avif",
        "./assets/img/Accessories/Hats_Caps/4.3.avif",
        "./assets/img/Accessories/Hats_Caps/4.4.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P071",
      name: "Sheer Ruffle Column Dress",
      type: "Women",
      cate: "Dresses",
      collection: "Spring-Summer",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Sheer Ruffle Column Dress is a stunning piece that combines elegance and modern design. Made from lightweight, sheer fabric, it features a ruffled neckline and a flattering column silhouette.",
      images: [
        "./assets/img/Collection/Seasonal/Spring-Summer/1.1.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/1.2.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/1.3.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P072",
      name: "Halter Maxi Suitcase Hat Look",
      type: "Accessories",
      cate: "Hats-Caps",
      collection: "Spring-Summer",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Halter Maxi Suitcase Hat Look is a trendy and versatile outfit perfect for warm weather. Made from lightweight fabric, it features a halter neckline and a flowing maxi skirt.",
      images: [
        "./assets/img/Collection/Seasonal/Spring-Summer/2.1.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/2.2.jpg",
        "./assets/img/Collection/Seasonal/Spring-Summer/2.3.jpg",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P073",
      name: "Ivory Double-Breasted Suit",
      type: "Men",
      cate: "Outerwear",
      collection: "Spring-Summer",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Ivory Double-Breasted Suit is a sophisticated and stylish outfit perfect for formal occasions. Made from high-quality fabric, it features a double-breasted design and a tailored fit.",
      images: [
        "./assets/img/Collection/Seasonal/Spring-Summer/3.1.jpg",
        "./assets/img/Collection/Seasonal/Spring-Summer/3.2.jpg",
        "./assets/img/Collection/Seasonal/Spring-Summer/3.3.jpg",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P074",
      name: "Mono Check Vest & Skirt Set",
      type: "Women",
      cate: "Dresses",
      collection: "Spring-Summer",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Mono Check Vest & Skirt Set is a chic and modern outfit perfect for any occasion. Made from high-quality fabric, it features a stylish check pattern and a flattering silhouette.",
      images: [
        "./assets/img/Collection/Seasonal/Spring-Summer/4.1.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/4.2.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/4.3.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/4.4.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P075",
      name: "Sand Tailored Blazer & Wide-Leg Trousers",
      type: "Men",
      cate: "Outerwear",
      collection: "Spring-Summer",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Sand Tailored Blazer & Wide-Leg Trousers is a sophisticated and stylish outfit perfect for formal occasions. Made from high-quality fabric, it features a tailored blazer and wide-leg trousers for a modern look.",
      images: [
        "./assets/img/Collection/Seasonal/Spring-Summer/5.1.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/5.2.jpg",
        "./assets/img/Collection/Seasonal/Spring-Summer/5.3.jpg",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P076",
      name: "Monochrome Check Tweed and Slit Mini Skirt",
      type: "Women",
      cate: "Dresses",
      collection: "Spring-Summer",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Monochrome Check Tweed and Slit Mini Skirt is a stylish and modern piece perfect for any occasion. Made from high-quality fabric, it features a chic check pattern and a flattering silhouette.",
      images: [
        "./assets/img/Collection/Seasonal/Spring-Summer/6.1.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/6.2.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/6.3.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/6.4.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P077",
      name: "Pastel Tweed Short Suit with Ruffled Bloom Collar",
      type: "Women",
      cate: "Dresses",
      collection: "Spring-Summer",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Pastel Tweed Short Suit with Ruffled Bloom Collar is a stylish and modern outfit perfect for any occasion. Made from high-quality fabric, it features a chic tweed pattern and a flattering silhouette.",
      images: [
        "./assets/img/Collection/Seasonal/Spring-Summer/7.1.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/7.2.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/7.3.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/7.4.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P078",
      name: "Logo Polo and High-Waisted Wide Trousers Look",
      type: "Men",
      cate: "Outerwear",
      collection: "Spring-Summer",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Logo Polo and High-Waisted Wide Trousers Look is a stylish and modern outfit perfect for any occasion. Made from high-quality fabric, it features a chic logo design and a flattering silhouette.",
      images: [
        "./assets/img/Collection/Seasonal/Spring-Summer/8.1.webp",
        "./assets/img/Collection/Seasonal/Spring-Summer/8.2.jpg",
        "./assets/img/Collection/Seasonal/Spring-Summer/8.3.jpg",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P079",
      name: "The Grand Bow Black Sparkle Mini Suit",
      type: "Women",
      cate: "Dresses",
      collection: "Winter-Autumn",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Grand Bow Black Sparkle Mini Suit is a stunning and elegant outfit perfect for special occasions. Made from high-quality fabric, it features a beautiful bow detail and a flattering silhouette.",
      images: [
        "./assets/img/Collection/Seasonal/Winter-Autumn/1.1.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/1.2.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/1.3.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/1.4.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/1.5.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/1.6.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P080",
      name: "Raspberry Knit Set with Pink Trims",
      type: "Women",
      cate: "Dresses",
      collection: "Winter-Autumn",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Raspberry Knit Set with Pink Trims is a stylish and comfortable outfit perfect for any occasion. Made from high-quality fabric, it features a chic knit design and a flattering silhouette.",
      images: [
        "./assets/img/Collection/Seasonal/Winter-Autumn/2.1.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/2.2.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/2.3.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/2.4.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/2.5.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/2.6.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P081",
      name: "Grey Quilted Workwear Suit",
      type: "Women",
      cate: "Dresses",
      collection: "Winter-Autumn",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Grey Quilted Workwear Suit is a stylish and modern outfit perfect for any occasion. Made from high-quality fabric, it features a chic quilted design and a flattering silhouette.",
      images: [
        "./assets/img/Collection/Seasonal/Winter-Autumn/3.1.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/3.2.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/3.3.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/3.4.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/3.5.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/3.6.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/3.7.webp",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P082",
      name: "Camo Floral Padded Jacket and Denim Shorts",
      type: "Men",
      cate: "Outerwear",
      collection: "Winter-Autumn",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Camo Floral Padded Jacket and Denim Shorts is a trendy and stylish outfit perfect for any occasion. Made from high-quality fabric, it features a chic camo floral design and a flattering silhouette.",
      images: [
        "./assets/img/Collection/Seasonal/Winter-Autumn/4.1.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/4.2.avif",
        "./assets/img/Collection/Seasonal/Winter-Autumn/4.3.avif",
        "./assets/img/Collection/Seasonal/Winter-Autumn/4.4.avif",
        "./assets/img/Collection/Seasonal/Winter-Autumn/4.5.avif",
        "./assets/img/Collection/Seasonal/Winter-Autumn/4.6.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P083",
      name: "Geometric Knit and Pink Utility Vest",
      type: "Men",
      cate: "Outerwear",
      collection: "Winter-Autumn",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Geometric Knit and Pink Utility Vest is a stylish and modern outfit perfect for any occasion. Made from high-quality fabric, it features a chic geometric knit design and a flattering silhouette.",
      images: [
        "./assets/img/Collection/Seasonal/Winter-Autumn/5.1.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/5.2.avif",
        "./assets/img/Collection/Seasonal/Winter-Autumn/5.3.avif",
        "./assets/img/Collection/Seasonal/Winter-Autumn/5.4.avif",
        "./assets/img/Collection/Seasonal/Winter-Autumn/5.5.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
    {
      id: "P084",
      name: "Camo Floral Padded Jacket and Denim Shorts",
      type: "Men",
      cate: "Outerwear",
      collection: "Winter-Autumn",
      costPrice: 100000,
      profitPercent: 50,
      price: 150000,
      color: ["blue"],
      productDesc:
        "The Camo Floral Padded Jacket and Denim Shorts is a trendy and stylish outfit perfect for any occasion. Made from high-quality fabric, it features a chic camo floral design and a flattering silhouette.",
      images: [
        "./assets/img/Collection/Seasonal/Winter-Autumn/6.1.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/6.2.webp",
        "./assets/img/Collection/Seasonal/Winter-Autumn/6.3.avif",
        "./assets/img/Collection/Seasonal/Winter-Autumn/6.4.avif",
        "./assets/img/Collection/Seasonal/Winter-Autumn/6.5.avif",
        "./assets/img/Collection/Seasonal/Winter-Autumn/6.6.avif",
      ],
      sizes: ["M", "L"],
      quantity: 11,
      hidden: false,
    },
  ];

  localStorage.setItem("products", JSON.stringify(products));
  console.log(
    "Product data with multiple images and sizes has been initialized."
  );
}

// ================= IMPORT ORDERS =================
if (!localStorage.getItem("imports")) {
  const imports = [
    {
      id: "I001",
      productId: "P001",
      productName: "Blue Cotton T-shirt",
      date: "2025-10-20",
      quantity: 10,
      price: 200000,
      total: 2000000,
      status: "Completed",
    },
    {
      id: "I002",
      productId: "P003",
      productName: "Blue Denim Jeans",
      date: "2025-10-21",
      quantity: 5,
      price: 280000,
      total: 1400000,
      status: "Pending",
    },
    {
      id: "I003",
      productId: "P004",
      productName: "Men’s Baseball Cap",
      date: "2025-10-22",
      quantity: 15,
      price: 100000,
      total: 1500000,
      status: "Pending",
    },
  ];
  localStorage.setItem("imports", JSON.stringify(imports));
}

// ================= CUSTOMER ORDERS =================
if (!localStorage.getItem("orders")) {
  const orders = [
    {
      id: "O005",
      customer: "Võ Nhựt Luân",
      username: "user1",
      customerPhone: "0395166079",
      customerAddress: "dhsg quan 5",
      date: "2025-11-02",
      items: [
        {
          productId: "P001",
          name: "Blue Cotton T-shirt",
          type: "Men",
          color: "blue",
          size: "M",
          quantity: 1,
          image: "./assets/20240827_99qstqYiE1.png",
          price: 250000,
        },
      ],
      total: 250000,
      paymentMethod: "COD",
      status: "New",
    },
  ];
  localStorage.setItem("orders", JSON.stringify(orders));
  console.log("Sample orders created (English version)");
}

// ================= SAMPLE CART =================
if (!localStorage.getItem("cart")) {
  const sampleCart = [
    {
      id: "P003",
      user: user1,
      name: "Blue Denim Jeans",
      type: "Jeans",
      price: 350000,
      productDesc: "Durable and stylish blue jeans for everyday use.",
      quantity: 1,
      color: "blue",
      size: "M",
      gender: "men",
      image: "./assets/ao1.avif",
    },
  ];
  localStorage.setItem("cart", JSON.stringify(sampleCart));
  console.log("Sample cart created");
}
